/* 出題の 30 枚。値は docs/06_deck.md（guide 03 の本文）から取っている */
import type { Card } from "./deck";

export const DECK: readonly Card[] = [
  {
    id: "match",
    section: "skeleton",
    name: "MATCH",
    role: "グラフの中から、指定した形に当てはまる組み合わせをすべて探して行にする。SQL の FROM + JOIN。",
    code: [
      { text: "// Grid Operations が持っているサービス", kind: "cm" },
      { text: "\n" },
      { text: "MATCH", kind: "kw" },
      { text: " (t:Team {name: " },
      { text: "'Grid Operations'", kind: "hl" },
      { text: "})-[:" },
      { text: "OWNS", kind: "rel" },
      { text: "]->(s:Service)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " s.name, s.language" },
    ],
    expected: "telemetry-ingest   Go\ngrid-monitor       Go\ndispatch-optimizer Python\n3 行",
    note: "カンマで複数のパターンを並べられます。このとき結合しているのはカンマではなく、共有された変数です。",
    warn: "デカルト積に注意。 共有変数のないパターンをカンマで並べると行数が掛け算になります。 (e:Engineer)-[:MEMBER_OF]->(t), (i:Incident)-[:AFFECTED]->(s) は 30 × 35 = 1,050 行。Neo4j も警告を出します。",
    runnable: true,
    mutates: false,
  },
  {
    id: "optional-match",
    section: "skeleton",
    name: "OPTIONAL MATCH",
    role: "見つからなくても行を捨てず、変数を null にして通す。SQL の LEFT OUTER JOIN。",
    code: [
      { text: "// 全エンジニアと、対応した件数", kind: "cm" },
      { text: "\n" },
      { text: "MATCH", kind: "kw" },
      { text: " (e:Engineer)\n" },
      { text: "OPTIONAL MATCH", kind: "kw" },
      { text: " (e)-[:" },
      { text: "RESPONDED_TO", kind: "rel" },
      { text: "]->(i:Incident)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " e.name, count(i) " },
      { text: "AS", kind: "kw" },
      { text: " n\n" },
      { text: "ORDER BY", kind: "kw" },
      { text: " n " },
      { text: "ASC LIMIT", kind: "kw" },
      { text: " 1" },
    ],
    expected: "Killua Zoldyck   0",
    note: "ここを普通の MATCH にすると Killua Zoldyck は 行ごと消えて結果は29人になります。「居ないこと」を出したいときに必須。",
    runnable: true,
    mutates: false,
  },
  {
    id: "where",
    section: "skeleton",
    name: "WHERE",
    role: "直前の MATCH または WITH の結果を絞る。置く位置で意味が変わる。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (i:Incident)\n" },
      { text: "WHERE", kind: "kw" },
      { text: " i.severity = " },
      { text: "'SEV1'", kind: "hl" },
      { text: "\n  " },
      { text: "AND", kind: "kw" },
      { text: " i.date >= date(" },
      { text: "'2026-01-01'", kind: "hl" },
      { text: ")\n" },
      { text: "RETURN", kind: "kw" },
      { text: " i.id, i.title" },
    ],
    expected:
      "INC-2118  Meter reader fleet disconnects…\nINC-2120  Billing engine OOM during…\n2 行",
    note: "使える述語：",
    runnable: true,
    mutates: false,
  },
  {
    id: "with",
    section: "skeleton",
    name: "WITH",
    role: "クエリを前半と後半に区切り、結果を渡す関所。集約・スコープ切断・集約後の絞り込みが同時に起きる。",
    code: [
      { text: "// 2チーム以上がまたがって対応したインシデントの数", kind: "cm" },
      { text: "\n" },
      { text: "MATCH", kind: "kw" },
      { text: " (e:Engineer)-[:" },
      { text: "MEMBER_OF", kind: "rel" },
      { text: "]->(t:Team), (e)-[:" },
      { text: "RESPONDED_TO", kind: "rel" },
      { text: "]->(i:Incident)\n" },
      { text: "WITH", kind: "kw" },
      { text: " " },
      { text: "i", kind: "hl" },
      { text: ", count(" },
      { text: "DISTINCT", kind: "kw" },
      { text: " t) " },
      { text: "AS", kind: "kw" },
      { text: " teams_involved   " },
      { text: "← i が暗黙のグループ化キー", kind: "cm" },
      { text: "\n" },
      { text: "WHERE", kind: "kw" },
      { text: " teams_involved > 1                    " },
      { text: "← 集約後の絞り込み = SQL の HAVING", kind: "cm" },
      { text: "\n" },
      { text: "RETURN", kind: "kw" },
      { text: " count(i) " },
      { text: "AS", kind: "kw" },
      { text: " cross_team_incidents" },
    ],
    expected: "52 行 → 20 行 → 13 行 → 1 行（13）",
    note: "3つの働きがあります。",
    warn: "キーは書かれていないので、うっかり増える。 WITH i, e, count(DISTINCT t) と項目を1つ足すとキーが (i, e) になり、 52行が畳まれず teams_involved は全部 1 になります。エラーは出ません。",
    runnable: true,
    mutates: false,
  },
  {
    id: "return",
    section: "skeleton",
    name: "RETURN",
    role: "最終的に何を返すか。AS で列名を付ける。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (s:Service)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " s.name " },
      { text: "AS", kind: "kw" },
      { text: " service,\n       s.language " },
      { text: "AS", kind: "kw" },
      { text: " lang,\n       s " },
      { text: "// ノードそのものも返せる", kind: "cm" },
    ],
    note: "ノードやリレーション、パスをそのまま返せます。Navigator が3Dで描けるのは、 RETURN n, r, m がノード実体を返しているからです。",
    runnable: false,
    mutates: false,
  },
  {
    id: "node",
    section: "patterns",
    name: "( ) — ノード",
    role: "丸括弧。中に 変数・ラベル・プロパティ を好きな組み合わせで書く。",
    code: [
      { text: "()                          " },
      { text: "何でもいい1ノード（匿名）", kind: "cm" },
      { text: "\n(s)                         " },
      { text: "変数 s に束縛", kind: "cm" },
      { text: "\n(:Service)                  " },
      { text: "Service ラベルだけ", kind: "cm" },
      { text: "\n(s:Service)                 " },
      { text: "両方", kind: "cm" },
      { text: "\n(s:Service {language:'Go'}) " },
      { text: "プロパティで絞る", kind: "cm" },
    ],
    note: "変数が要らないところは省くのが読みやすい書き方です。 (:Service {name:'auth-service'}) のように、後で使わない中継ノードは無名にします。",
    runnable: false,
    mutates: false,
  },
  {
    id: "edge",
    section: "patterns",
    name: "-[ ]-> — リレーション",
    role: "角括弧と矢印。向きは「探索の通行方向」を決める。",
    code: [
      { text: "-[:DEPENDS_ON]->   " },
      { text: "左が始点", kind: "cm" },
      { text: "\n<-[:DEPENDS_ON]-   " },
      { text: "右が始点", kind: "cm" },
      { text: "\n-[:DEPENDS_ON]-    " },
      { text: "向き不問（両方通る）", kind: "cm" },
      { text: "\n-[r:DEPENDS_ON]->  " },
      { text: "変数 r に束縛（r.prop が読める）", kind: "cm" },
      { text: "\n-[:OWNS|AFFECTED]-> " },
      { text: "複数の型のどれか", kind: "cm" },
      { text: "\n-->                " },
      { text: "型不問", kind: "cm" },
    ],
    expected:
      "customer-portal を起点に\n-[:DEPENDS_ON]->  →  4 件（依存する先）\n<-[:DEPENDS_ON]-  →  1 件（依存される元）",
    runnable: true,
    mutates: false,
  },
  {
    id: "varlen",
    section: "patterns",
    name: "*1..3 — 可変長パス",
    role: "同じ型のエッジを1〜3回続けて辿る。深さが未知の問いに効く。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (:Service {name:" },
      { text: "'customer-portal'", kind: "hl" },
      { text: "})\n      -[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "*1..3", kind: "hl" },
      { text: "]->(up:Service)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " collect(" },
      { text: "DISTINCT", kind: "kw" },
      { text: " up.name)" },
    ],
    expected:
      "14 パス → DISTINCT 7 件\napi-gateway, auth-service, billing-engine,\nmobile-api, meter-reader, payment-gateway,\ntariff-service",
    note: "返るのはノードではなくパス。同じノードに複数経路で着けばその回数だけ行が出るので DISTINCT がほぼ必須です。同一パス内での同じエッジの再利用は Cypher が禁じているため、矢印を辿ると一周して戻れてしまうグラフでも無限ループにはなりません。",
    runnable: true,
    mutates: false,
  },
  {
    id: "path",
    section: "patterns",
    name: "p = (…) — パス変数",
    role: "マッチしたパス全体を変数に取る。証跡（evidence path）を見せるときの定番。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " " },
      { text: "p", kind: "hl" },
      { text: " = (e:Engineer {name:" },
      { text: "'Winry Rockbell'", kind: "hl" },
      { text: "})\n        -[:" },
      { text: "RESPONDED_TO", kind: "rel" },
      { text: "]->(:Incident)\n        -[:" },
      { text: "AFFECTED", kind: "rel" },
      { text: "]->(:Service)\n        -[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "]->(:Service {name:" },
      { text: "'payment-gateway'", kind: "hl" },
      { text: "})\n" },
      { text: "RETURN", kind: "kw" },
      { text: " [n " },
      { text: "IN", kind: "kw" },
      { text: " nodes(p) | coalesce(n.name, n.id)]" },
    ],
    expected: "[Winry Rockbell, INC-2105,\n billing-engine, payment-gateway]\n1 行",
    note: "条件を満たすパスがちょうど1本しかないので、1行だけ返ります。これが 「Winry は payment-gateway に繋がっている」の証跡そのものです — どのインシデント経由で、どのサービスを挟んで繋がったのかが1行に出ています。 INC-2105 だけ id なのは Incident が name を持たないためで、 そこを coalesce が吸収しています。",
    runnable: true,
    mutates: false,
  },
  {
    id: "shortest",
    section: "patterns",
    name: "shortestPath / allShortestPaths",
    role: "2点間の最短経路。探索は幅優先で、全パス列挙より圧倒的に速い。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (a:Service {name:" },
      { text: "'customer-portal'", kind: "hl" },
      { text: "}),\n      (b:Service {name:" },
      { text: "'telemetry-ingest'", kind: "hl" },
      { text: "})\n" },
      { text: "MATCH", kind: "kw" },
      { text: " p = shortestPath((a)-[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "*]-(b))\n" },
      { text: "RETURN", kind: "kw" },
      { text: " [n " },
      { text: "IN", kind: "kw" },
      { text: " nodes(p) | n.name], length(p)" },
    ],
    expected: "customer-portal → outage-notifier\n  → grid-monitor → telemetry-ingest\nlength = 3",
    warn: "向きを付けると答えが消えます。 上の例の -[:DEPENDS_ON*]- を -[:DEPENDS_ON*]-> にすると 0 行。有向では customer-portal から telemetry-ingest に到達できないためです （reporting-service からなら有向で2ホップ）。",
    runnable: true,
    mutates: false,
  },
  {
    id: "exists",
    section: "patterns",
    name: "EXISTS { } / COUNT { }",
    role: "「そういう繋がりがあるか／いくつあるか」を、行を増やさずに問う。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (i:Incident)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " i.id,\n  " },
      { text: "EXISTS", kind: "kw" },
      { text: " { (i)-[:" },
      { text: "AFFECTED", kind: "rel" },
      { text: "]->(:Service)\n             -[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "]->(:Service {name:" },
      { text: "'payment-gateway'", kind: "hl" },
      { text: "}) }\n    " },
      { text: "AS", kind: "kw" },
      { text: " qualifies,\n  " },
      { text: "COUNT", kind: "kw" },
      { text: " { (i)<-[:" },
      { text: "RESPONDED_TO", kind: "rel" },
      { text: "]-() } " },
      { text: "AS", kind: "kw" },
      { text: " responders" },
    ],
    expected:
      "i.id       qualifies   responders\nINC-2120   true        3\nINC-2104   false       2",
    note: "通常の MATCH で書くと行が増えてしまう判定を、列として取れるのが利点です。 WHERE NOT EXISTS { … } で「〜が無いもの」も書けます。",
    runnable: true,
    mutates: false,
  },
  {
    id: "orderby",
    section: "shaping",
    name: "ORDER BY",
    role: "並べ替え。WITH の後にも RETURN の後にも置ける。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (i:Incident)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " i.severity, count(*) " },
      { text: "AS", kind: "kw" },
      { text: " n\n" },
      { text: "ORDER BY", kind: "kw" },
      { text: " n " },
      { text: "DESC", kind: "kw" },
    ],
    expected: "SEV2   9\nSEV1   6\nSEV3   5",
    note: "null は昇順で最後、降順で最初に来ます。",
    runnable: true,
    mutates: false,
  },
  {
    id: "skiplimit",
    section: "shaping",
    name: "SKIP / LIMIT",
    role: "件数を切る。ページングにも、探索の暴走止めにも使う。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (s:Service)<-[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "]-(d:Service)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " s.name, count(d) " },
      { text: "AS", kind: "kw" },
      { text: " dependents\n" },
      { text: "ORDER BY", kind: "kw" },
      { text: " dependents " },
      { text: "DESC", kind: "kw" },
      { text: ", s.name\n" },
      { text: "SKIP", kind: "kw" },
      { text: " 0 " },
      { text: "LIMIT", kind: "kw" },
      { text: " 2" },
    ],
    expected: "auth-service     4\nbilling-engine   3",
    note: "WITH … LIMIT を途中に挟むと、後続の処理が扱う行を先に減らせます。 重い探索の前に置くと効きます。",
    warn: "同数のときの順序は保証されません。 このデータは3位が data-lake-sync / grid-monitor / meter-reader / telemetry-ingest の 4件同点（各2）なので、LIMIT 3 は実行のたびに違う1件を返しうる。 タイブレークの第2キー（上例の s.name）を必ず入れます。",
    runnable: true,
    mutates: false,
  },
  {
    id: "distinct",
    section: "shaping",
    name: "DISTINCT",
    role: "重複を落とす。RETURN 全体にも、集約関数の中にも掛けられる。",
    code: [
      { text: "RETURN DISTINCT", kind: "kw" },
      { text: " up.name       " },
      { text: "行の重複を落とす", kind: "cm" },
      { text: "\ncount(" },
      { text: "DISTINCT", kind: "kw" },
      { text: " t)           " },
      { text: "集約する値の重複を落とす", kind: "cm" },
      { text: "\ncollect(" },
      { text: "DISTINCT", kind: "kw" },
      { text: " t.name)    " },
      { text: "同上", kind: "cm" },
    ],
    warn: "この2つは別物です。 count(t) は行数、count(DISTINCT t) は種類数。 cross-team の例では前者が 20、後者が 13 になり、答えが変わります。",
    runnable: false,
    mutates: false,
  },
  {
    id: "union",
    section: "shaping",
    name: "UNION / UNION ALL",
    role: "2つのクエリの結果を縦に繋ぐ。列名と列数が一致している必要がある。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (s:Service {language:" },
      { text: "'Go'", kind: "hl" },
      { text: "})\n" },
      { text: "RETURN", kind: "kw" },
      { text: " s.name " },
      { text: "AS", kind: "kw" },
      { text: " name, " },
      { text: "'Go'", kind: "hl" },
      { text: " " },
      { text: "AS", kind: "kw" },
      { text: " kind\n" },
      { text: "UNION", kind: "kw" },
      { text: "\n" },
      { text: "MATCH", kind: "kw" },
      { text: " (t:Team)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " t.name " },
      { text: "AS", kind: "kw" },
      { text: " name, " },
      { text: "'Team'", kind: "hl" },
      { text: " " },
      { text: "AS", kind: "kw" },
      { text: " kind" },
    ],
    expected: "Go のサービス 5 + チーム 8 = 13 行",
    note: "UNION は重複を落とし、UNION ALL は落としません。",
    runnable: true,
    mutates: false,
  },
  {
    id: "aggregates",
    section: "lists",
    name: "count / sum / avg / min / max",
    role: "集約関数。置いた瞬間に、集約でない項目がグループ化キーになる。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (t:Team)<-[:" },
      { text: "MEMBER_OF", kind: "rel" },
      { text: "]-(e:Engineer)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " t.name, count(e) " },
      { text: "AS", kind: "kw" },
      { text: " members\n" },
      { text: "ORDER BY", kind: "kw" },
      { text: " members " },
      { text: "DESC", kind: "kw" },
      { text: ", t.name" },
    ],
    expected:
      "Core Infrastructure   4\nCustomer Platform     4\n…\nField Systems         3\nForecasting & AI      3",
    note: "count(*) は行数、count(x) は x が null でない行数。OPTIONAL MATCH と組むとこの差が効きます。",
    runnable: true,
    mutates: false,
  },
  {
    id: "collect",
    section: "lists",
    name: "collect( )",
    role: "複数行を1つのリストに畳む。「一覧を1行で見せる」ときの主力。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (t:Team)-[:" },
      { text: "OWNS", kind: "rel" },
      { text: "]->(s:Service)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " t.name, collect(s.name) " },
      { text: "AS", kind: "kw" },
      { text: " services" },
    ],
    expected:
      "Grid Operations\n  [telemetry-ingest, grid-monitor,\n   dispatch-optimizer]\nPayments & Billing\n  [payment-gateway, billing-engine,\n   tariff-service]",
    note: "null は自動的に除かれます。OPTIONAL MATCH の後に置くと 「該当なしは空リスト []」という扱いやすい形になります。",
    runnable: true,
    mutates: false,
  },
  {
    id: "unwind",
    section: "lists",
    name: "UNWIND",
    role: "collect の逆。リストを行に開く。データ投入の定番。",
    code: [
      { text: "// session3 のロードはこの形", kind: "cm" },
      { text: "\n" },
      { text: "UNWIND", kind: "kw" },
      { text: " $rows " },
      { text: "AS", kind: "kw" },
      { text: " r\n" },
      { text: "MERGE", kind: "kw" },
      { text: " (s:Service {name: r.name})\n" },
      { text: "SET", kind: "kw" },
      { text: " s.description = r.description,\n    s.language    = r.language" },
    ],
    expected: "SEV1  6\nSEV2  9",
    note: "Python のリストをパラメータで渡し、1行ずつに開いて処理します。 15件のサービスを1クエリで投入できるのはこれのおかげです。",
    runnable: true,
    mutates: false,
  },
  {
    id: "comprehension",
    section: "lists",
    name: "パターン内包表記",
    role: "パターンの結果をその場でリストにする。WITH を挟まずに済む。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (i:Incident)\n" },
      { text: "WHERE", kind: "kw" },
      { text: " i.severity = " },
      { text: "'SEV1'", kind: "hl" },
      { text: "\n" },
      { text: "RETURN", kind: "kw" },
      { text: " i.id,\n  " },
      { text: "[(i)-[:AFFECTED]->(x:Service) | x.name]", kind: "hl" },
      { text: " " },
      { text: "AS", kind: "kw" },
      { text: " affected" },
    ],
    expected:
      "INC-2103  [customer-portal, auth-service]\nINC-2120  [billing-engine, reporting-service]\n6 行（SEV1 は 6 件）",
    note: "[パターン | 取り出す式] という形。 リスト内包表記 [x IN list WHERE 条件 | 式] も同じ書き方です。",
    runnable: true,
    mutates: false,
  },
  {
    id: "listfn",
    section: "lists",
    name: "リスト関数・述語",
    role: "リストを検査したり畳んだりする。",
    code: [
      { text: "size(list)          " },
      { text: "要素数", kind: "cm" },
      { text: "\nhead(list) / last(list)\nrange(1, 5)         " },
      { text: "[1,2,3,4,5]", kind: "cm" },
      { text: "\nreverse(list)\nreduce(a = 0, x " },
      { text: "IN", kind: "kw" },
      { text: " list | a + x)\n\n" },
      { text: "ALL", kind: "kw" },
      { text: "  (x " },
      { text: "IN", kind: "kw" },
      { text: " list " },
      { text: "WHERE", kind: "kw" },
      { text: " 条件)\n" },
      { text: "ANY", kind: "kw" },
      { text: "  (x " },
      { text: "IN", kind: "kw" },
      { text: " list " },
      { text: "WHERE", kind: "kw" },
      { text: " 条件)\n" },
      { text: "NONE", kind: "kw" },
      { text: " (x " },
      { text: "IN", kind: "kw" },
      { text: " list " },
      { text: "WHERE", kind: "kw" },
      { text: " 条件)\n" },
      { text: "SINGLE", kind: "kw" },
      { text: "(x " },
      { text: "IN", kind: "kw" },
      { text: " list " },
      { text: "WHERE", kind: "kw" },
      { text: " 条件)" },
    ],
    expected:
      "[grid-monitor, telemetry-ingest]\n[api-gateway, auth-service]\n2 行（Go は 5 サービスだが連続する所は少ない）",
    runnable: true,
    mutates: false,
  },
  {
    id: "case",
    section: "lists",
    name: "CASE / coalesce",
    role: "条件分岐と null 埋め。表示の整形でよく使う。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (i:Incident)\n" },
      { text: "RETURN", kind: "kw" },
      { text: " i.severity,\n  " },
      { text: "CASE", kind: "kw" },
      { text: " i.severity\n    " },
      { text: "WHEN", kind: "kw" },
      { text: " " },
      { text: "'SEV1'", kind: "hl" },
      { text: " " },
      { text: "THEN", kind: "kw" },
      { text: " " },
      { text: "'即応'", kind: "hl" },
      { text: "\n    " },
      { text: "WHEN", kind: "kw" },
      { text: " " },
      { text: "'SEV2'", kind: "hl" },
      { text: " " },
      { text: "THEN", kind: "kw" },
      { text: " " },
      { text: "'当日'", kind: "hl" },
      { text: "\n    " },
      { text: "ELSE", kind: "kw" },
      { text: " " },
      { text: "'翌営業日'", kind: "hl" },
      { text: "\n  " },
      { text: "END", kind: "kw" },
      { text: " " },
      { text: "AS", kind: "kw" },
      { text: " policy" },
    ],
    note: "CASE WHEN 条件 THEN … END という汎用形もあります （値の一致ではなく任意の条件で分岐したいとき）。",
    runnable: false,
    mutates: false,
  },
  {
    id: "create",
    section: "writing",
    name: "CREATE",
    role: "無条件に作る。重複チェックをしないので、再実行すると増える。",
    code: [
      { text: "CREATE", kind: "kw" },
      { text: " (s:Service {name: " },
      { text: "'billing-engine'", kind: "hl" },
      { text: "})\n" },
      { text: "// 2回実行 = 同名ノードが2つできる", kind: "cm" },
    ],
    note: "ノートブックが CREATE ではなく MERGE を使っているのは、 セルの再実行が安全であるようにするためです。",
    runnable: false,
    mutates: true,
  },
  {
    id: "merge",
    section: "writing",
    name: "MERGE",
    role: "「あれば使う、無ければ作る」。冪等なので何度実行しても同じ状態になる。",
    code: [
      { text: "UNWIND", kind: "kw" },
      { text: " $rows " },
      { text: "AS", kind: "kw" },
      { text: " r\n" },
      { text: "MERGE", kind: "kw" },
      { text: " (t:Team {name: r.name})\n" },
      { text: "ON CREATE SET", kind: "kw" },
      { text: " t.created = date()\n" },
      { text: "ON MATCH SET", kind: "kw" },
      { text: "  t.seen    = date()\n" },
      { text: "SET", kind: "kw" },
      { text: " t.focus = r.focus" },
    ],
    note: "リレーションを MERGE するときは、両端が先に存在している必要があります。 だから session3 の投入はノード → リレーションの順です。",
    warn: "MERGE のパターン全体が一致条件です。 MERGE (s:Service {name:'x', language:'Go'}) は 「name も language も一致するノード」を探し、無ければ両方を持つ新ノードを作ります。 キーだけで MERGE し、残りは SET で埋めるのが安全な型です。",
    runnable: false,
    mutates: true,
  },
  {
    id: "set",
    section: "writing",
    name: "SET / REMOVE",
    role: "プロパティとラベルの付け外し。",
    code: [
      { text: "SET", kind: "kw" },
      { text: " s.language = " },
      { text: "'Go'", kind: "hl" },
      { text: "          " },
      { text: "1つ設定", kind: "cm" },
      { text: "\n" },
      { text: "SET", kind: "kw" },
      { text: " s += {tier: 1, sla: 99.9}  " },
      { text: "まとめて追加/更新", kind: "cm" },
      { text: "\n" },
      { text: "SET", kind: "kw" },
      { text: " s =  {name: s.name}        " },
      { text: "全置換（他は消える）", kind: "cm" },
      { text: "\n" },
      { text: "SET", kind: "kw" },
      { text: " s:Critical                 " },
      { text: "ラベルを足す", kind: "cm" },
      { text: "\n\n" },
      { text: "REMOVE", kind: "kw" },
      { text: " s.sla                    " },
      { text: "プロパティを消す", kind: "cm" },
      { text: "\n" },
      { text: "REMOVE", kind: "kw" },
      { text: " s:Critical              " },
      { text: "ラベルを外す", kind: "cm" },
    ],
    warn: "= と += は別物。 = は書かなかったプロパティを消します。",
    runnable: false,
    mutates: true,
  },
  {
    id: "delete",
    section: "writing",
    name: "DELETE / DETACH DELETE",
    role: "消す。リレーションが残っているノードは普通には消せない。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (n) " },
      { text: "DETACH DELETE", kind: "kw" },
      { text: " n\n" },
      { text: "// 繋がっているリレーションごと全消し", kind: "cm" },
      { text: "\n" },
      { text: "// session3 冒頭の「まっさらにする」がこれ", kind: "cm" },
    ],
    note: "DELETE n だけだと、n に繋がるリレーションが1本でもあればエラーになります。 DETACH がそれを先に消してくれます。",
    warn: "ワークショップ用インスタンス限定の操作です。 実データベースでは絶対に流さないこと。",
    runnable: false,
    mutates: true,
  },
  {
    id: "foreach",
    section: "writing",
    name: "FOREACH",
    role: "リストの各要素に更新処理を掛ける。更新専用で、読み取りは書けない。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " p = (:Service {name:" },
      { text: "'customer-portal'", kind: "hl" },
      { text: "})\n          -[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "*1..3]->(:Service)\n" },
      { text: "FOREACH", kind: "kw" },
      { text: " (n " },
      { text: "IN", kind: "kw" },
      { text: " nodes(p) | " },
      { text: "SET", kind: "kw" },
      { text: " n:Upstream)" },
    ],
    expected: "実行前  (billing-engine:Service)\n実行後  (billing-engine:Service:Upstream)",
    note: "n:Upstream は Upstream というラベルを1枚足すという意味です。 n に「Upstream」という文字列が入るのではありません — それをやりたいなら SET n.tag = 'Upstream' と書きます。 ラベルは Service や Incident と同じノードの種類を表す印で、 1つのノードに何枚でも重ねられます。",
    warn: "起点にも印が付きます。 nodes(p) はパスの全ノードなので customer-portal 自身も含まれ、印が付くのは 8 件（依存先の7件 + 起点）。 依存先の7件だけにしたいなら tail(nodes(p)) で先頭を落とします。",
    runnable: false,
    mutates: true,
  },
  {
    id: "callsub",
    section: "subqueries",
    name: "CALL { } — サブクエリ",
    role: "独立したクエリを中に埋め込む。「行ごとに上位N件」が書ける。",
    code: [
      { text: "MATCH", kind: "kw" },
      { text: " (t:Team)\n" },
      { text: "CALL", kind: "kw" },
      { text: " {\n  " },
      { text: "WITH", kind: "kw" },
      { text: " t                      " },
      { text: "← 外の変数を持ち込む宣言", kind: "cm" },
      { text: "\n  " },
      { text: "MATCH", kind: "kw" },
      { text: " (t)-[:" },
      { text: "OWNS", kind: "rel" },
      { text: "]->(s:Service)\n  " },
      { text: "RETURN", kind: "kw" },
      { text: " s.name " },
      { text: "AS", kind: "kw" },
      { text: " svc\n  " },
      { text: "ORDER BY", kind: "kw" },
      { text: " s.name " },
      { text: "LIMIT", kind: "kw" },
      { text: " 1\n}\n" },
      { text: "RETURN", kind: "kw" },
      { text: " t.name, svc" },
    ],
    expected: "チームごとに1件ずつ = 8 行",
    note: "外側の LIMIT では「全体で1件」になってしまうところを、 行ごとの LIMIT にできるのが要点です。",
    runnable: true,
    mutates: false,
  },
  {
    id: "callproc",
    section: "subqueries",
    name: "CALL … YIELD — プロシージャ",
    role: "組み込みの手続きを呼ぶ。スキーマの確認によく使う。",
    code: [
      { text: "CALL", kind: "kw" },
      { text: " db.labels()                 " },
      { text: "ラベル一覧", kind: "cm" },
      { text: "\n" },
      { text: "CALL", kind: "kw" },
      { text: " db.relationshipTypes()      " },
      { text: "エッジ型一覧", kind: "cm" },
      { text: "\n" },
      { text: "CALL", kind: "kw" },
      { text: " db.schema.visualization()   " },
      { text: "スキーマ図", kind: "cm" },
      { text: "\n" },
      { text: "SHOW", kind: "kw" },
      { text: " INDEXES / " },
      { text: "SHOW", kind: "kw" },
      { text: " CONSTRAINTS" },
    ],
    expected: "db.labels() → Team, Engineer,\n             Service, Incident",
    note: "初めて触るデータベースの中身を掴むとき、まずこれを叩きます。",
    runnable: true,
    mutates: false,
  },
  {
    id: "schema",
    section: "subqueries",
    name: "CONSTRAINT / INDEX",
    role: "一意性の保証と、起点ノード探索の高速化。",
    code: [
      { text: "CREATE CONSTRAINT", kind: "kw" },
      { text: " svc_name " },
      { text: "IF NOT EXISTS", kind: "kw" },
      { text: "\n" },
      { text: "FOR", kind: "kw" },
      { text: " (s:Service) " },
      { text: "REQUIRE", kind: "kw" },
      { text: " s.name " },
      { text: "IS UNIQUE", kind: "kw" },
      { text: ";\n\n" },
      { text: "CREATE INDEX", kind: "kw" },
      { text: " inc_sev " },
      { text: "IF NOT EXISTS", kind: "kw" },
      { text: "\n" },
      { text: "FOR", kind: "kw" },
      { text: " (i:Incident) " },
      { text: "ON", kind: "kw" },
      { text: " (i.severity);" },
    ],
    note: "一意性制約を張ると、その裏側でインデックスも自動的に作られます。",
    warn: "session3 のノートブックはこれを張っていません。 そのため {name:'customer-portal'} はラベルスキャンです。15件なので体感差はありませんが、 制約の前後で EXPLAIN を比べると NodeByLabelScan → NodeUniqueIndexSeek の変化が見えます。",
    runnable: false,
    mutates: false,
  },
  {
    id: "explain",
    section: "subqueries",
    name: "EXPLAIN / PROFILE",
    role: "実行計画を見る。同じクエリの頭に付ける2つのモードで、出る情報が違う。",
    code: [
      { text: "EXPLAIN", kind: "kw" },
      { text: " " },
      { text: "MATCH", kind: "kw" },
      { text: " (:Service {name:" },
      { text: "'customer-portal'", kind: "hl" },
      { text: "})\n        -[:" },
      { text: "DEPENDS_ON", kind: "rel" },
      { text: "*1..3]->(up:Service) " },
      { text: "RETURN", kind: "kw" },
      { text: " up" },
    ],
    expected: "NodeByLabelScan(:Service)\n  Filter (name = …)\n    VarLengthExpand(All)",
    note: "EXPLAIN はクエリを流しません。プランナが立てた計画（演算子の並び）と 推定行数だけを返し、実データには触れません。重いクエリを投げる前に 「その形で大丈夫か」を確かめるためのものです。",
    warn: "db hits は PROFILE でしか出ません。 「実際に何レコード触ったか」は走らせてみないと分からないためです。 EXPLAIN で読めるのは演算子の並びと推定行数までなので、 速さを測りたいときは PROFILE、形だけ見たいときは EXPLAIN と使い分けます。",
    runnable: true,
    mutates: false,
  },
];
